ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 36, in main
    settings_dict = benedict(settings_yaml)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\__init__.py", line 54, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keyattr\keyattr_dict.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keypath\keypath_dict.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keylist\keylist_dict.py", line 8, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 20, in __init__
    d = IODict._decode_init(arg, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 31, in _decode_init
    return IODict._decode(s, format, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 42, in _decode
    raise ValueError(
C
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 54, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1822_brightfield_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1822_brightfield_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1822_fluorescence_zeiss_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1822_brightfield_cos7_n3_f0.5
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1822_brightfield_cos7_n3_f1
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 55, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1840_brightfield_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1840_brightfield_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1840_fluorescence_zeiss_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1840_brightfield_cos7_n3_f0.5
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20231114_1840_brightfield_cos7_n3_f1
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 55, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231118_0200_isim_cos7
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231118_0201_isim_u2os
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231118_0201_isim
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 59, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231216_0202_isim_cos7
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231216_0203_isim_u2os
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231216_0203_isim
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 59, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231223_0202_isim_cos7
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231223_0203_isim_u2os
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231223_0203_isim
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 59, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231230_0202_isim_cos7
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231230_0203_isim_u2os
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20231230_0203_isim
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 59, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 52, in distributed_train
    p.starmap(train, zip(folders, gpus, settings))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20240106_0202_isim_cos7
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20240106_0203_isim_u2os
\\lebsrv2.epfl.ch\LEB_SHARED\SHARED\_Scientific projects\ADA_WS_JCL\230222_MitoSplitNet_TrainingSet_U2OS_iSIM\training_data\20240106_0203_isim
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 59, in main
    distributed_train(folders, gpus, settings)
  File "C:\Internal\deep_events\deep-events\deep_events\train.py", line 49, in distributed_train
    os.env['TF_GPU_ALLOCATOR'] = "cuda_malloc_async"
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1016_brightfield_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1017_fluorescence_zeiss_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1017_fluorescence_zeiss_cos7
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1017_brightfield_cos7_n3_f0.2
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1017_brightfield_cos7_n3_f0.2
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1018_brightfield_cos7_n3_f1
\\lebnas1.epfl.ch\microsc125\deep_events\data\original_data\training_data\20240112_1018_brightfield_cos7_n3_f1
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 40, in main
    folders, settings = gather_settings(settings_dict)
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 84, in gather_settings
    folder = prepare_for_prompt(Path(settings_dict["folder"]), settings_dict[key],
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 67, in prepare_for_prompt
    all_images, all_gt = load_folder(folder, db_files, training_folder, n_timepoints, fps)
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 130, in load_folder
    images, ground_truth = load_tifs(folder)
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 168, in load_tifs
    images = tifffile.imread(image_file).astype(np.float32)
  File "C:\Internal\deep_events\.env\lib\site-packages\tifffile\tifffile.py", line 1008, in imread
    with TiffFile(
  File "C:\Internal\deep_events\.env\lib\site-packages\tifffile\tifffile.py", line 3832, in __init__
    fh = FileHandle(file, mode=mode, name=name, offset=offset, size=size)
  File "C:\Internal\deep_events\.env\lib\site-packages\tifffile\tifffile.py", line 13088, in __init__
    self.open()
  File "C:\Internal\deep_events\.env\lib\site-packages\tifffile\tifffile.py", line 13103, in open
    self._fh = open(self._file, self._mode)  # type: ignore
C:\Internal\deep_events\scheduled_settings\mito_ideas.yaml
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 41, in main
    folders, settings = gather_settings(settings_dict)
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 85, in gather_settings
    folder = prepare_for_prompt(Path(settings_dict["folder"]), settings_dict[key],
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 76, in prepare_for_prompt
    all_images, all_gt = load_folder(folder, db_files, training_folder, n_timepoints, fps,
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 156, in load_folder
    original_fps = benedict(db_file)["fps"]
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\__init__.py", line 68, in __getitem__
    return self._cast(super().__getitem__(key))
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keypath\keypath_dict.py", line 31, in __getitem__
    return super().__getitem__(self._parse_key(key))
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keylist\keylist_dict.py", line 40, in __getitem__
    return super().__getitem__(key)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\base\base_dict.py", line 58, in __getitem__
    return self._dict[key]
C:\Internal\deep_events\scheduled_settings\phase_pearls.yaml
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 41, in main
    folders, settings = gather_settings(settings_dict)
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 85, in gather_settings
    folder = prepare_for_prompt(Path(settings_dict["folder"]), settings_dict[key],
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 76, in prepare_for_prompt
    all_images, all_gt = load_folder(folder, db_files, training_folder, n_timepoints, fps,
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 185, in load_folder
    all_images[train_eval] = np.concatenate(all_images[train_eval])
  File "<__array_function__ internals>", line 180, in concatenate
C:\Internal\deep_events\scheduled_settings\mito_ideas.yaml
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 41, in main
    folders, settings = gather_settings(settings_dict)
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 85, in gather_settings
    folder = prepare_for_prompt(Path(settings_dict["folder"]), settings_dict[key],
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 81, in prepare_for_prompt
    all_images, all_gt = load_folder(folder, db_files, training_folder, n_timepoints, fps,
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 190, in load_folder
    all_images[train_eval] = np.concatenate(all_images[train_eval])
  File "<__array_function__ internals>", line 180, in concatenate
C:\Internal\deep_events\scheduled_settings\mito_ideas.yaml
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 41, in main
    folders, settings = gather_settings(settings_dict)
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 85, in gather_settings
    folder = prepare_for_prompt(Path(settings_dict["folder"]), settings_dict[key],
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 84, in prepare_for_prompt
    all_images, all_gt = load_folder(folder, db_files, training_folder, n_timepoints, fps,
  File "C:\Internal\deep_events\deep-events\deep_events\prepare_training.py", line 193, in load_folder
    all_images[train_eval] = np.concatenate(all_images[train_eval])
  File "<__array_function__ internals>", line 180, in concatenate
C:\Internal\deep_events\scheduled_settings\mito_ideas.yaml
Maybe data has moved?
ERROR 
  File "C:\Internal\deep_events\deep-events\scheduled_train\scheduled_train.py", line 38, in main
    settings_dict = benedict(settings_yaml)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\__init__.py", line 54, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keyattr\keyattr_dict.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keypath\keypath_dict.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\keylist\keylist_dict.py", line 8, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 20, in __init__
    d = IODict._decode_init(arg, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 31, in _decode_init
    return IODict._decode(s, format, **kwargs)
  File "C:\Internal\deep_events\.env\lib\site-packages\benedict\dicts\io\io_dict.py", line 42, in _decode
    raise ValueError(
C:\Internal\deep_events\scheduled_settings\mito_ideas.yaml
Maybe data has moved?
